config:
<<<<<<< HEAD
  info: master branch,springcloud-config/config-test.yml version=4
=======
  info: master branch,springcloud-config/config-test.yml version=5
>>>>>>> 5c999fd (config-test version5.0)
